# Default values for couchbase-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: couchbase/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "community-7.0.2"

## Additional environment variables to be added to couchbase pods
env: {}
## env: 
## variable1: value1
## variable2: value2

# Couchbase Automatic intialize Setup  Cluster 
##
Setup:
  enabled: true
  services: data,index,query,fts
  clusterRamSize: 512
  clusterIndexRmasize: 256
  clusterFtsRamsize: 256
  


## Specify image pull secrets used in the deployment
imagePullSecrets: []
## imagePullSecrets:
##   - name: some-registry
##   - name: another-registry


nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

rbac:
  # Specifies whether RBAC resources should be created
  ##
  create: true

  resources:
    - pods
    - secrets


serviceAccount:
  # Specifies whether a service account should be created
  ##
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  ##
  name: ""

## Couchbase server pod termination grace period
##
terminationGracePeriodSeconds: 120

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# couchbase Administrator Username
##
Username: "Administrator"

# couchbase Administrator Password
##
Password: "Administrator"


service:
  type: ClusterIP
  port: 8091
  # nodePort: ""
  
ingress:
  enabled: false
  className: ""
  annotations: {}
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "http-cookie"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod-cluster"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #    hosts:
  #      - chart-example.local
  #  - secretName: chart-example-tls

persistence:
  ## 
  enabled: true
  ## Must match those of existing PV or dynamic provisioner
  ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  accessMode: ReadWriteOnce
  ## Couchbase data Persistent Volume size
  size: "8Gi"
  # storageClass: "-"

# Couchbase NFS Backup 
##
backup:
  enabled: false
  accessmode: ReadWriteOnce
# Total NFS persistence volume Capacity Size
#
  capacity:
    storage: 10Gi
# NFS PersistenceVolumeClaim Size
#
  Pvc:
   size: 5Gi
# NFS StorageClassName
##
  storageClassName: "-"
# NFS Server Data path and Server
##
  nfs:
    path: -
    server: -
    
# Couchbase Auto Backup Job
# Must be used with NFS Backup parameters 
##
backupjob:
    enabled: false
    schedule: "*/5 * * * *"

# Couchbase Failover after is rebalance Job
##
failover:
     enabled: false
     schedule: "*/10 * * * *"
 
# It allows new pods to be added to the cluster automatically after the number of replicas increases.
##
postscale:
     enabled: false
     schedule: "*/15 * * * *"


startupProbe: {}
#  periodSeconds: 60
#  failureThreshold: 3
#  successThreshold: 1
#  timeoutSeconds: 5


livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 5


# Create specific secret
##
existingRootSecret: ""


secret:
    ## Secret annotations
    ##
    annotations: {}


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Date time Configuration
location: Europe/Istanbul

## Node labels for node-exporter pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Node tolerations for node-exporter scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

## Pod affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
