# Define backup storage volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-pvc
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
