# Define backup storage volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-pvc
  namespace: couchbase-cluster
spec:
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
