apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: couchbase-cluster-autoscaling
  namespace: couchbase-cluster
spec:
  maxReplicas: 3
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: couchbase-cluster 
  targetCPUUtilizationPercentage: 50
