apiVersion: batch/v1
kind: CronJob
metadata:
  name: autoupdate-cluster-job
  namespace: couchbase-cluster
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: autoupdate-cluster
            image: docker.io/couchbase/server:community-7.0.2
            command: 
              - /bin/sh
              - -c
              - |
                /scripts/autoupdate-node.sh
            volumeMounts:
            - name: autoupdate-cluster-job
              mountPath: /scripts
          volumes:
            - name: cautoupdate-cluster-job
              configMap:
                name: autoupdate-cluster-job
                defaultMode: 0777
          restartPolicy: Never

