apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: couchbase-read-rolebinding
  namespace: couchbase-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-read-role
subjects:
- namespace: couchbase-cluster
  kind: ServiceAccount
  name: couchbase-serviceaccount
