kind: ConfigMap 
apiVersion: v1 
metadata:
  name: couchbase-rebelance
  namespace: couchbase-cluster
data:
  rebalance-node.sh: |+
    #!/bin/bash
    #dynamic values
    replicas=3
    hostname0=couchbase-cluster-0.couchbase-cluster-svc.couchbase-cluster.svc.kubeceofg.ithinka.local
    password=123123
    services="data,index,query,fts"
    cluster_ramsize=512
    cluster_index_ramsize=256
    cluster_fts_ramsize=256

    cs=`couchbase-cli server-list -c $hostname0:8091 --username Administrator --password "$password" | grep " healthy active" | wc -l`

    if [ $cs -eq 0 ]
    then
    #static first pod name
    couchbase-cli node-init -c $hostname0 -u Administrator -p $password \
    --node-init-hostname "$hostname0"

    #setup init
    couchbase-cli cluster-init -c $hostname0 \
    --cluster-username Administrator \
    --cluster-password $password \
    --services $services \
    --cluster-ramsize $cluster_ramsize \
    --cluster-index-ramsize $cluster_index_ramsize \
    --cluster-fts-ramsize $cluster_fts_ramsize

    #add server and rebalance
    for (( a=1 ; a<=$replicas-1; a++ ));
    do
    echo "$hostname0" | sed "s/-0/-${a}/g" > hostx
    hostx=`cat hostx`
    couchbase-cli server-add -c $hostname0:8091 --username Administrator \
     --password $password --server-add $hostx:8091 \
     --server-add-username Administrator --server-add-password $password \
     --services $services
    couchbase-cli rebalance -c $hostname0:8091 -u Administrator -p $password
    done
    fi
