---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase-cluster
  namespace: couchbase-cluster
  labels:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
spec:
  replicas: 3
  serviceName: couchbase-cluster-svc
  selector:
    matchLabels:
      app.kubernetes.io/component: couchbase-server
      app.kubernetes.io/name: couchbase-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/component: couchbase-server
        app.kubernetes.io/name: couchbase-cluster
    spec:
      serviceAccountName: couchbase-serviceaccount 
      terminationGracePeriodSeconds: 0
      containers:
        - name: couchbase-cluster
          image: docker.io/couchbase/server:community-7.1.1
          resources:
            limits:
              cpu: 100m
              memory: 2Gi
          ports:
          - name: couchbase-port
            containerPort: 8091
          - name: couchbase-xdcr
            containerPort: 8092
          - name: couchbase-rest
            containerPort: 8093
          - name: couchbase-event
            containerPort: 8096
          - name: couchbase-data
            containerPort: 11210
          - name: couchbase-moxi
            containerPort: 11211
          volumeMounts:
          - name: couchbase-cluster-pvc
            mountPath: /opt/couchbase/var
          env:
          - name: COUCHBASE_MASTER
            value: "couchbase-cluster-0.couchbase-cluster-svc.couchbase-cluster.svc.ithinka.cluster.local"
          - name: AUTO_REBALANCE
            value: "true"
          - name: CLUSTER_CUSTOM_USERNAME
            valueFrom:
              secretKeyRef:
                name: couchbase-administrator
                key: username
          - name: CLUSTER_CUSTOM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchbase-administrator
                key: password
  volumeClaimTemplates:
    - metadata:
        name: couchbase-cluster-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: "-"
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-cluster-svc
  namespace: couchbase-cluster
  labels:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
spec:
  ports:
  - name: couchbase-port
    port: 8091
    targetPort: 8091
  - name: couchbase-xdcr
    port: 8092
    targetPort: 8092
  - name: couchbase-rest
    port: 8093
    targetPort: 8093
  - name: couchbase-event
    port: 8096
    targetPort: 8096
  - name: couchbase-data
    port: 11210
    targetPort: 11210
  - name: couchbase-moxi
    port: 11211
    targetPort: 11211
  # *.couchbase.default.svc.cluster.local
  clusterIP: None
  selector:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-cluster-ui
  namespace: couchbase-cluster
  labels:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-ui
spec:
  ports:
  - name: couchbase-port
    port: 8091
    targetPort: 8091
  selector:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
  sessionAffinity: ClientIP
  type: ClusterIP
