{{- if .Values.backup.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "couchbase-cluster.fullname" . }}-pvc
spec:
  storageClassName: "{{ .Values.backup.storageClassName }}"
  resources:
    requests:
      storage: {{ .Values.backup.size }}
  accessModes:
    - {{ .Values.backup.accessmode }}

{{- end }}
