{{- if .Values.backupjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: couchbase-cluster-backup-create
spec:
  schedule: "{{ .Values.backupjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-script
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command: ["sh", "-c" ,"cbbackup http://{{ include "couchbase-cluster.fullname" . }}-0.{{ include "couchbase-cluster.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}  /couchbase/backup -u Administrator -p {{ .Values.Password }}"]
            volumeMounts:
            - name: "couchbase-backup"
              mountPath: "/couchbase/backup"
          initContainers:
          - name: setup
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            command:
               - /bin/sh
               - -c
               - |
                 curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
                 install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
                 chmod +x kubectl
                 mkdir -p ~/.local/bin
                 mv ./kubectl ~/.local/bin/kubectl
                 #PASSWORD=`kubectl get {{ template "couchbase-cluster.fullname" . }}-o "jsonpath={.data['password']}" | base64 -d`
          volumes:
           - name: couchbase-backup
             persistentVolumeClaim:
                claimName: backup-pvc
          restartPolicy: OnFailure

 {{- end -}}


