{{- if .Values.backupjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: failover-cluster-job
  namespace: couchbase-cluster
spec:
  schedule: "{{ .Values.failover.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: failover-cluster
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command: 
              - /bin/sh
              - -c
              - |
                /scripts/failover-node.sh
            volumeMounts:
            - name: failover-cluster
              mountPath: /scripts
          volumes:
            - name: failover-cluster
              configMap:
                name: failover-cluster
                defaultMode: 0777
          restartPolicy: Never
 {{- end -}}
