kind: ConfigMap 
apiVersion: v1 
metadata:
  name: postscale-cluster
  namespace: couchbase-cluster
data:
  postscale-node.sh: |+
    #!/bin/bash
    replicas={{ .Values.replicaCount }}
    hostname0={{ include "couchbase-cluster.fullname" . }}-0.{{ include "couchbase-cluster.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
    password={{ .Values.Password }}
    username= {{ .Values.Username }}
    cs=`couchbase-cli server-list -c $hostname0:8091 --username "$username" --password "$password" | wc -l`
    if [ $replicas -gt $cs ]
    then
    services="{{ .Values.Setup.services }}"
    cluster_ramsize={{ .Values.Setup.clusterRamSize }}
    cluster_index_ramsize={{ .Values.Setup.clusterIndexRmasize }}
    cluster_fts_ramsize={{ .Values.Setup.clusterFtsRamsize }}
    #add server and rebalance
    for (( a=1 ; a<=$replicas-1; a++ ));
    do
    echo "$hostname0" | sed "s/-0/-${a}/g" > hostx
    hostx=`cat hostx`
    couchbase-cli server-add -c $hostname0:8091 --username Administrator \
    --password $password --server-add $hostx:8091 \
    --server-add-username $username --server-add-password $password \
    --services $services
    couchbase-cli rebalance -c $hostname0:8091 -u $username -p $password
    done
    fi
