{{- if not .Values.existingRootSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.fullname" . }}
  labels:
{{- include "couchbase-cluster.labels" . | nindent 4 }}
{{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  username: {{ .Values.Username | b64enc | quote }}
  password: {{ .Values.Password | b64enc | quote }}
{{- end }}
