{{- if .Values.Setup.enabled -}}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: couchbase-rebelance
data:
  rebalance-node.sh: |+
    #!/bin/bash
    #dynamic values
    replicas={{ .Values.replicaCount }}
    hostname0={{ include "couchbase-cluster.fullname" . }}-0.{{ include "couchbase-cluster.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
    password={{ .Values.existingRootSecret | default (include "couchbase-cluster.fullname" .) }}
    services="{{ .Values.Setup.services }}"
    cluster_ramsize={{ .Values.Setup.clusterRamSize }}
    cluster_index_ramsize={{ .Values.Setup.clusterIndexRmasize }}
    cluster_fts_ramsize={{ .Values.Setup.clusterFtsRamsize }}
    cs=`couchbase-cli server-list -c $hostname0:8091 --username Administrator --password "$password" | grep " healthy active" | wc -l`

    if [ $cs -eq 0 ]
    then
    #static first pod name
    couchbase-cli node-init -c $hostname0 -u Administrator -p $password \
    --node-init-hostname "$hostname0"

    #setup init
    couchbase-cli cluster-init -c $hostname0 \
    --cluster-username Administrator \
    --cluster-password $password \
    --services $services \
    --cluster-ramsize $cluster_ramsize \
    --cluster-index-ramsize $cluster_index_ramsize \
    --cluster-fts-ramsize $cluster_fts_ramsize

    #add server and rebalance
    for (( a=1 ; a<=$replicas-1; a++ ));
    do
    echo "$hostname0" | sed "s/-0/-${a}/g" > hostx
    hostx=`cat hostx`
    couchbase-cli server-add -c $hostname0:8091 --username Administrator \
    --password $password --server-add $hostx:8091 \
    --server-add-username Administrator --server-add-password $password \
    --services $services
    couchbase-cli rebalance -c $hostname0:8091 -u Administrator -p $password
    done
    fi
{{- end }}
